<?php

class SomethingDigital_SearchPerf_Model_Index_Action_Fulltext_Refresh_Changelog extends Enterprise_CatalogSearch_Model_Index_Action_Fulltext_Refresh_Changelog
{
    use SomethingDigital_SearchPerf_Trait_ResetsSearchResults;
}
